# This is a basic workflow to help you get started with Actions

name: Test Homebrew

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Runs a single command using the runners shell
    - name: download peacemakr-cli
      run: |
        brew tap peacemakr-io/peacemakr
        brew install peacemakr-io/peacemakr/peacemakr-cli

    # Runs a set of commands using the runners shell
    - name: Run peacemakr
      env:
        PEACEMAKR_APIKEY: SQTCdQxcHqLciaWJ2nEQeAEnDb/i6LQjq0RZeqXwcGM=
      run: |
        time echo "hello secure world" | peacemakr-cli -encrypt | peacemakr-cli -decrypt
